### ISSUE TITLE
Does this still work in Chrome Version 48.0.2564.97 m  

### ISSUE THREAD

**Issue by bwb1066** [chrisdeely/ForceCORS#11] opened 2016-02-03 20:37 UTC
My responses from a JIRA cloud instance's REST API do not have the access control header set to the value I have added into your plugin UI.

Please help, thanks.

bwb1066

**Comment by chrisdeely** [comment] 2016-02-03 22:07
Can you provide any additional detail here? What headers are you attempting to add and how are you validating whether or not they are applied?

**Comment by chrisdeely** [comment] 2016-02-03 22:12
Also, there is a bug that is still listed as open on the Chromium site which prevents the values from being displayed in the Network panel: https://code.google.com/p/chromium/issues/detail?id=258064

**Comment by bwb1066** [comment] 2016-02-04 02:10
When I make an ajax request, the plugin badge increments, indicating it has
intercepted the request, but the error in the chrome inspector says:

XMLHttpRequest cannot load https://myco.atlassian.net/issue/createmeta
https://factset.atlassian.net/issue/createmeta. No
'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://myco.com http://is.factset.com/' is therefore not allowed
access. The response had HTTP status code 404.

**Comment by bwb1066** [comment] 2016-02-04 02:12
forgot the add the
settings for  https://myco.atlassian.net/*

Header Name
Access-Control-Allow-Origin

Header Value
http://myco.com

**Comment by chrisdeely** [comment] 2016-02-04 15:09
Two things that might help:
- I don't think you need to include the protocol in the Allow Origin
  header. Try just "myco.com"
- Chrome often reports CORS errors when _anything_ goes wrong during an
  cross-domain XHR, even if the headers happen to be correct. In the example
  you posted, the response code was 404, indicating that the server could not
  find the requested URL. This could mean the URL is wrong or the server does
  not support OPTIONS requests at all (which this extension currently cannot
  help with)

**Comment by benmarte** [comment] 2016-02-13 02:43
Does this work with POST and PUT?

This is what my settings look like.

<img width="1027" alt="screen shot 2016-02-12 at 9 39 52 pm" src="https://cloud.githubusercontent.com/assets/693275/13025271/4867b038-d1d1-11e5-947f-708bb3a5e459.png">

But I still get errors in my console:

XMLHttpRequest cannot load http://192.168.99.100:8080/argos-admin/communities/1. Method DELETE is not allowed by Access-Control-Allow-Methods in preflight response.

XMLHttpRequest cannot load http://192.168.99.100:8080/argos-admin/communities/1. Method PUT is not allowed by Access-Control-Allow-Methods in preflight response.

This is my Chrome version: Version 48.0.2564.109 (64-bit)

Thanks.

**Comment by chrisdeely** [comment] 2016-02-13 15:48
Yes, all methods should be supported.

The problem is that you should only have a single entry for
"Access-Control-Allow-Methods" with comma-separated values like
"GET,POST,PUT,DELETE"

**Comment by chrisdeely** [comment] 2016-02-19 03:55
@bwb1066 @benmarte I'm hoping the responses above led you to solutions? Clear to close this report?

**Comment by benmarte** [comment] 2016-02-19 15:56
@chrisdeely yes, thanks for the info feel free to close it.

**Closed as completed** 2016-06-06 15:45 UTC
